title: "Добро пожаловать в мой блог"
date: 2019-02-06
author: Skyder
email: skyder@inbox.ru
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: нет
github_username:  skyder

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
